spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: bookuser
    url: jdbc:mysql://127.0.0.1:3306/bookdb2?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    password: password
  liquibase:
    user: bookadmin
    password: password
  sql:
    init:
      mode: always
  flyway:
    user: bookadmin
    password: password
  jpa:
    hibernate:
      ddl-auto: validate
